dataset: tinyImageNet
backbone: EfficientNet-b3
pretrain: True
blur: True
blur: True
gauss_kernel_size: 3 #3,7,11
num_comp: 15
num_subclasses: 2 # num of subclasses per superclass for selected vague classes

num_workers: 0

#experiment type
exp_type: 1
saved_path_pretrain: None #for exp3

train: True
test: True

epochs: 3
init_lr: 0.0001

uncertainty: True 

# loss functions
mse: True 
digamma: False 
log: False 

kl_reg: False  #KL in the ENN 
kl_lam: 0.0001

kl_reg_pretrain: False  #KL in experiment 3
kl_lam_pretrain: 0.0001
forward_kl_pretrain: True 

entropy_reg: False
entropy_lam: 0.0001
