dataset: tinyimagenet
backbone: EfficientNet-b3
pretrain: True
blur: True
gauss_kernel_size: 3 #3,7,11

num_comp: 15
num_subclasses: 2 # num of subclasses per superclass for selected vague classes

num_workers: 0

#experiment type
exp_type: 4 # 5
saved_path_teacher: None #for exp3

train: True
test: True

batch_size: 64
epochs: 60
init_lr: 0.00001
milestone1: 110
milestone2: 130

use_uncertainty: True 

# loss functions
mse: False 
digamma: True 
log: False 

kl_reg: False  #KL in the ENN 
kl_lam: 0.0

kl_reg_teacher: False  #KL in experiment 3
kl_lam_teacher: 0.0
forward_kl_teacher: True 

entropy_reg: True
entropy_lam: 1

ce_lam: 0
