dataset: tinyimagenet
backbone: EfficientNet-b3
pretrain: True
blur: True
gauss_kernel_size: 3

num_comp: 25

uncertainty: True

batch_size: 64
epochs: 50
init_lr: 0.00001
milestone1: 100
milestone2: 150

train: True
test: True